package com.dynamide.util;

import java.io.File;

/** Implement this interface to listen to callbacks generated by FileTools.directoryDiver
 *
 */
public interface IFileDiverListener {

    /** @param diveID This identifies the callback so that you know which thing you are doing if you use the
     *   callback interface for two tasks within one class, or within multiple threads.
     *
     *  @see FileTools#directoryDiver
     */
    public void onFile(String diveID, File directory, File file, String filename, String relativePath);

    /** @param diveID This identifies the callback so that you know which thing you are doing if you use the
     *   callback interface for two tasks within one class, or within multiple threads.
     *
     * @return true if you wish to continue diving INTO the named directory, otherwise
     *   return false to skip the contents of the named directory.
     *
     *  @see FileTools#directoryDiver
     */
    public boolean onDirectory(String diveID, File directory, String dirname, String relativePath);
}
