    import java.util.*;
    import java.io.*;

    //for mail:
    import java.util.Properties;
    import javax.mail.*;
    import javax.mail.internet.*;

    String subject = "Hi";
    String body = "Hi";
    String host = "smtp.earthlink.net";
    String from = "tester@dynamide.com";
    String to = "to@dynamide.com";
    String to2 = "to2@dynamide.com";

    // Get system properties
    Properties props = System.getProperties();

    // Setup mail server
    props.setProperty("mail.smtp.host", host);
    //only needed for custom port: props.setProperty("mail.smtp.port", "5025");

    // Get session
    javax.mail.Session session = javax.mail.Session.getDefaultInstance(props, null);

    // Define message
    MimeMessage message = new MimeMessage(session);
    message.setFrom(new InternetAddress(from));
    message.addRecipient(Message.RecipientType.TO, new InternetAddress(to));
    message.addRecipient(Message.RecipientType.TO, new InternetAddress(to2));
    message.setSubject(subject);
    message.setContent(body, "text/html");

    // Send message
    Transport.send(message);